# fly.toml app configuration file generated for smoke-server on 2025-03-22T08:41:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smoke-server'
primary_region = 'mad'

[build]
dockerfile = '../Dockerfile'
build-target = 'runner'

[build.args]
PROJECT_NAME = 'smoke-test'

[env]
PORT = '4000'

[[services]]
protocol = 'tcp'
internal_port = 4000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services.ports]]
port = 4000

[[vm]]
size = 'shared-cpu-1x'
