# fly.toml app configuration file generated for prime-time on 2025-04-08T01:58:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prime-time'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '4000'

[[services]]
  protocol = 'tcp'
  internal_port = 4000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 4000

[[vm]]
  size = 'shared-cpu-1x'
